[[redirects]]
  from = "/instagram"
  to = "https://www.instagram.com/zerokelvinru/"
  status = 200
  force = true
[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404
[[headers]]
  for = "/model/*"
  [headers.values]
    Content-Type = "model/vnd.usdz+zip"
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"