backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "/src/images/uploads"
public_folder: "/dist/images/uploads"
collections:
  - name: 'products' # Used in routes, e.g., /admin/collections/blog
    label: 'Products' # Used in the UI
    folder: 'src/products' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Price', name: 'price', widget: 'string' }
      - { label: "Layout", name: "layout", widget: "hidden", default: "product.njk" }
      - { label: 'Image', name: 'img', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: true}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'informations' # Used in routes, e.g., /admin/collections/blog
    label: 'Странички с информацией' # Used in the UI
    folder: 'src/pages/information/' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Link', name: 'permalink', widget: 'string', default: "/example/" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "template_main.njk" }
      - { label: 'Body', name: 'body', widget: 'markdown' }